# Generated by Django 4.2.3 on 2023-07-30 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('style', models.CharField(max_length=200)),
                ('pattern', models.CharField(max_length=100)),
                ('climate', models.CharField(max_length=200)),
                ('publish_date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('category_id', models.ForeignKey(auto_created=True, on_delete=django.db.models.deletion.CASCADE, to='Clothing.category')),
            ],
        ),
        migrations.CreateModel(
            name='ImageProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('detail_product_id', models.ForeignKey(auto_created=True, on_delete=django.db.models.deletion.CASCADE, to='Clothing.product')),
            ],
        ),
        migrations.CreateModel(
            name='DetailProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('sale_price', models.IntegerField()),
                ('product_id', models.ForeignKey(auto_created=True, on_delete=django.db.models.deletion.CASCADE, to='Clothing.product')),
            ],
        ),
    ]
