# Generated by Django 4.2.3 on 2023-07-31 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clothing', '0003_alter_category_id_alter_detailproduct_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField( max_length=100),
            preserve_default=False,
        ),
    ]
