# Generated by Django 4.2.3 on 2023-08-01 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clothing', '0004_product_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageproduct',
            name='image',
            field=models.TextField(),
        ),
    ]
